### ISSUE TITLE
support CORS

### ISSUE THREAD

**Issue by osallou** [bio-tools/biotoolsRegistry#13]
registry does not support CORS (cross origin requests) preventing querying the registry directly from a browser with Javascript. This complexifies the integration with other tools.

Would be nice to get CORS access, at least for GET requests

**Comment by joncison** [comment]
this done a while ago

**Comment by fbacall** [comment]
Is CORS still supported? I'm having trouble making browser requests from TeSS:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://bio.tools/api/tool?q=&sort=score. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200
```

**Comment by veitveit** [comment]
@fbacall I think it still is. Do you still have that issue?

**Comment by veitveit** [comment]
Needs to be looked into.

**Comment by veitveit** [comment]
@fbacall It should be fixed now.

**Comment by carissableker** [comment]
I'm trying to make a simple widget for our node tool collection, and still getting a CORS error:

```
Access to fetch at 'https://bio.tools/api/tool/?collectionID=%22ELIXIR-SI%22&format=json' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
GET https://bio.tools/api/tool/?collectionID=%22ELIXIR-SI%22&format=json net::ERR_FAILED 200 (OK)
```

```javascript
function fetchBioToolsCollection(query) {
    const url = `https://bio.tools/api/tool/?collectionID="ELIXIR-SI"&format=json`;
    fetch(url)
        .then(response => response.json())
        .then(console.log(data))
}
fetchBioToolsCollection();

```

**Comment by anitamnd** [comment]
Hey @carissableker! Sorry for the delay, this should be fixed now.
