### ISSUE TITLE
Citation count should be displayed

### ISSUE THREAD

**Issue by Federico77z** [bio-tools/biotoolsRegistry#323]
Since there is a "Sort by Citation count" function the actual citation count should be displayed or it becomes hard for an user to even understand if the function is properly working. It could be displayed near the name for "compact" visualization and in its own column for the "detailed" visualization.

**Comment by joncison** [comment]
also fixed in https://dev.bio.tools ... pls. take a look and close this if you're happy  cc @piotrgithub1

**Comment by Federico77z** [comment]
Sorry but in dev.bio.tools it appears in the tool's entry (and it's ok, i like it) but still not in the search results.

**Comment by joncison** [comment]
I understand, thanks!  cc @piotrgithub1 for consideration

**Comment by hansioan** [comment]
Citation counts are there, but they are missing for some of the publications.
The citation counts are part of the `publications` property.
Examples:
- Go to: https://bio.tools/?sort=citationCount&ord=desc
- switch to `Detailed` view
- make sure the `publications` column appears in the table

**Comment by joncison** [comment]
The request is to have citation count (also publication date, see https://github.com/bio-tools/biotoolsRegistry/issues/324) on the "Compact" view .. given that we can now sort by those fields.

**Comment by krab1k** [comment]
Why some tools have publication and citations details and some have not?

E.g., https://bio.tools/MOLE3269 includes the information, but for https://bio.tools/atomicchargecalculator it's not provided. Both publications are in the same Open Access journal.

**Comment by joncison** [comment]
@baileqi can you answer @krab1k  ?

**Comment by joncison** [comment]
@krab1k the problem you posted has gone away (publication details are shown for both https://bio.tools/mole and https://bio.tools/atomicchargecalculator).  But if you encounter a similar problem, please post a separate issue for it.

**Comment by joncison** [comment]
@Federico77z : @hansioan and I have discussed this issue, which is a bit tricky to fix.

1. First, calculate sum of citations of publications labelled as "Primary" (https://github.com/bio-tools/biotoolsRegistry/issues/346)
2. Render this value discretely in the "Compact view"
3. Identify the latest publication of type "Primary" and render the DOI in the "Compact" view

We'll get to this, but for now, you'll just have to use the "Detailed" view

**Comment by hansioan** [comment]
We also need to render addition date and updated date since we can also sort by those.
